modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Command17/Hammering/issues"
license = "MIT"

[[mods]]
modId = "hammering"
version = "${version}"
displayName = "Hammering"
authors = "Command17"
description = '''
Adds hammers, that's it.
'''
logoFile = "assets/hammering/icon.png"

[[dependencies.hammering]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hammering]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hammering]]
modId = "enchantedbooklib"
type = "required"
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "hammering.mixins.json"
